content:
  - name: posts
    label: 글 목록
    path: content
    type: collection
    view:
      fields: [title, created, status]
    fields:
      - name: title
        label: 제목
        type: string
      - name: created
        label: 생성일
        type: date
        options:
          format: YYYY-MM-DD
      - name: status
        label: 상태
        type: select
        options:
          values: [draft, published]
      - name: tags
        label: 태그
        type: string
        list: true
      - name: body
        label: 본문
        type: rich-text
